Remove use of Black entirely
The Black formatter was conflicting with Ruff.

```
$ just fix
…
"/usr/bin/just" _compile requirements.prod.in requirements.prod.txt
"/usr/bin/just" _compile requirements.dev.in requirements.dev.txt
$BIN/black .
All done! ✨ 🍰 ✨
6 files left unchanged.
$BIN/ruff check --fix .
Found 2 errors (2 fixed, 0 remaining).
```

then:

```
$ just check
…
$BIN/black --check .
would reformat /workspaces/osgithub/osgithub/__init__.py
would reformat /workspaces/osgithub/setup.py

Oh no! 💥 💔 💥
2 files would be reformatted, 4 files would be left unchanged.
error: Recipe `black` failed on line 98 with exit code 1
```

It's possible that maybe we could tweak the settings of one or other to
match. But it's preferable to simplify things here.

Let's just remove Black because using Ruff alone:

* fixes this issue
* removes several dependencies
* is faster
* is how we work with other repositories